package com.wiryadev.bootstrapiconscompose.bootstrapicons

import androidx.compose.ui.graphics.vector.ImageVector
import com.wiryadev.bootstrapiconscompose.BootstrapIcons
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Alarm
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignBottom
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignCenter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignEnd
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignMiddle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignStart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AlignTop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Alt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.App
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AppIndicator
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Archive
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Arrow90degDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Arrow90degLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Arrow90degRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Arrow90degUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowBarDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowBarLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowBarRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowBarUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowClockwise
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowCounterclockwise
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownLeftCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownLeftSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownRightCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownRightSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownShort
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowDownUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowLeftCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowLeftRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowLeftShort
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowLeftSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowRepeat
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowReturnLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowReturnRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowRightCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowRightShort
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowRightSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpLeftCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpLeftSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpRightCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpRightSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpShort
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowUpSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsAngleContract
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsAngleExpand
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsCollapse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsExpand
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsFullscreen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ArrowsMove
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.AspectRatio
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Asterisk
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.At
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Award
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Back
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Backspace
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BackspaceReverse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Badge3d
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Badge4k
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Badge8k
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeAd
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeAr
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeCc
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeHd
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeTm
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeVo
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeVr
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BadgeWc
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bag
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BagCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BagDash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BagPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BagX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bank
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bank2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BarChart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BarChartLine
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BarChartSteps
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Basket
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Basket2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Basket3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Battery
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BatteryCharging
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BatteryFull
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BatteryHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bell
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BellSlash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bezier
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bezier2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bicycle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Binoculars
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BlockquoteLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BlockquoteRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Book
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bookmark
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkDash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkHeart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkStar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BookmarkX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bookmarks
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bookshelf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bootstrap
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BootstrapReboot
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Border
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderAll
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderBottom
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderCenter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderInner
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderMiddle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderOuter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderStyle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderTop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BorderWidth
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoundingBox
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoundingBoxCircles
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Box
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowDownLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowDownRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInDownLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInDownRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInUpLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowInUpRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowUpLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxArrowUpRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BoxSeam
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Braces
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bricks
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Briefcase
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BrightnessAltHigh
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BrightnessAltLow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BrightnessHigh
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BrightnessLow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Broadcast
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.BroadcastPin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Brush
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bucket
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bug
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Building
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Bullseye
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calculator
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Check
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Date
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Day
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Event
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Minus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Month
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Plus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Range
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2Week
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar2X
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar3Event
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar3Range
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar3Week
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar4
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar4Event
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar4Range
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Calendar4Week
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarDate
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarDay
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarEvent
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarMonth
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarRange
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarWeek
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CalendarX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Camera
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Camera2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CameraReels
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CameraVideo
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CameraVideoOff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Capslock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CardChecklist
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CardHeading
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CardImage
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CardList
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CardText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretDownSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretLeftSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretRightSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CaretUpSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cart2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cart3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cart4
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CartCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CartDash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CartPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CartX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CashCoin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CashStack
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cast
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Chat
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatDots
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatLeftDots
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatLeftQuote
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatLeftText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatQuote
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatRightDots
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatRightQuote
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatRightText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatSquareDots
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatSquareQuote
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatSquareText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChatText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Check
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Check2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Check2All
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Check2Circle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Check2Square
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CheckAll
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CheckCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CheckLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CheckSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarContract
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarExpand
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronBarUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronCompactDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronCompactLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronCompactRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronCompactUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronContract
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronDoubleDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronDoubleLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronDoubleRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronDoubleUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronExpand
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ChevronUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Circle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CircleHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CircleSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Clipboard
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClipboardCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClipboardData
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClipboardMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClipboardPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClipboardX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Clock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ClockHistory
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cloud
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudDownload
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudDrizzle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudFog
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudFog2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudHail
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudHaze
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudHaze1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudLightning
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudLightningRain
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudMoon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudRain
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudRainHeavy
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudSlash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudSleet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudSnow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudSun
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CloudUpload
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Clouds
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cloudy
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Code
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CodeSlash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CodeSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Coin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Collection
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CollectionPlay
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Columns
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ColumnsGap
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Command
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Compass
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cone
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ConeStriped
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Controller
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cpu
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CreditCard
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CreditCard2Back
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CreditCard2Front
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Crop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cup
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CupStraw
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyBitcoin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyDollar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyEuro
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyExchange
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyPound
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CurrencyYen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Cursor
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.CursorText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DashCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DashCircleDotted
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DashLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DashSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DashSquareDotted
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Diagram2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Diagram3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Diamond
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DiamondHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice4
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice5
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dice6
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Disc
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Discord
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Display
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DistributeHorizontal
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DistributeVertical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DoorClosed
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DoorOpen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Dot
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Download
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Droplet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.DropletHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Earbuds
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Easel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Egg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EggFried
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Eject
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiAngry
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiDizzy
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiExpressionless
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiFrown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiHeartEyes
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiLaughing
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiNeutral
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiSmile
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiSmileUpsideDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiSunglasses
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EmojiWink
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Envelope
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EnvelopeOpen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Eraser
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Exclamation
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationDiamond
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationOctagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ExclamationTriangle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Exclude
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Eye
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.EyeSlash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Eyedropper
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Eyeglasses
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Facebook
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.File
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileBarGraph
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileBinary
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileBreak
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileCode
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileDiff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmark
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkBarGraph
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkBinary
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkBreak
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkCode
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkDiff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkEasel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkExcel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkFont
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkImage
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkLock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkLock2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkMedical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkMusic
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPdf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPerson
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPlay
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPost
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkPpt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkRichtext
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkRuled
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkSlides
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkSpreadsheet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkWord
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEarmarkZip
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileEasel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileExcel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileFont
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileImage
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileLock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileLock2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileMedical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileMusic
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePdf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePerson
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePlay
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePost
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilePpt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileRichtext
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileRuled
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileSlides
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileSpreadsheet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileWord
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FileZip
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Files
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilesAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Film
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Filter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilterCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilterLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilterRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FilterSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Flag
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Flower1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Flower2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Flower3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Folder
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Folder2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Folder2Open
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FolderCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FolderMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FolderPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FolderSymlink
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FolderX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Fonts
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Forward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Front
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Fullscreen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.FullscreenExit
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Funnel
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Gear
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GearWide
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GearWideConnected
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Gem
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GenderAmbiguous
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GenderFemale
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GenderMale
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GenderTrans
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Geo
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GeoAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Gift
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Github
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Globe
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Globe2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Google
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GraphDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GraphUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid1x2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid3x2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid3x2Gap
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid3x3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Grid3x3Gap
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GripHorizontal
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.GripVertical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hammer
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HandIndex
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HandIndexThumb
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HandThumbsDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HandThumbsUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Handbag
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hdd
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HddNetwork
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HddRack
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HddStack
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Headphones
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Headset
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HeadsetVr
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Heart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HeartHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Heptagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HeptagonHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hexagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HexagonHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hourglass
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HourglassBottom
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HourglassSplit
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HourglassTop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.House
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.HouseDoor
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hr
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Hurricane
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Image
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ImageAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Images
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Inbox
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Inboxes
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Info
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.InfoCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.InfoLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.InfoSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.InputCursor
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.InputCursorText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Instagram
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Intersect
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Journal
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalAlbum
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalArrowDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalArrowUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalBookmark
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalCode
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalMedical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalRichtext
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalText
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JournalX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Journals
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Joystick
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Justify
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JustifyLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.JustifyRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Kanban
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Key
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Keyboard
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Ladder
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Lamp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Laptop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayerBackward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayerForward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Layers
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayersHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutSidebar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutSidebarInset
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutSidebarInsetReverse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutSidebarReverse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutSplit
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutTextSidebar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutTextSidebarReverse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutTextWindow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutTextWindowReverse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutThreeColumns
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LayoutWtf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LifePreserver
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Lightbulb
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LightbulbOff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Lightning
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.LightningCharge
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Link
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Link45deg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Linkedin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.List
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListNested
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListOl
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListStars
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListTask
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ListUl
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Lock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mailbox
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mailbox2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Map
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Markdown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mask
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mastodon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Megaphone
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MenuApp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MenuButton
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MenuButtonWide
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MenuDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MenuUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Messenger
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mic
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MicMute
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Minecart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MinecartLoaded
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Moisture
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Moon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MoonStars
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mouse
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mouse2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Mouse3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MusicNote
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MusicNoteBeamed
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MusicNoteList
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.MusicPlayer
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Newspaper
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.NodeMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.NodePlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Nut
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Octagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.OctagonHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Option
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Outlet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PaintBucket
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Palette
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Palette2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Paperclip
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Paragraph
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PatchCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PatchExclamation
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PatchMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PatchPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PatchQuestion
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pause
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PauseBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PauseCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Peace
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pencil
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PencilSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pentagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PentagonHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.People
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Percent
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Person
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonBadge
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonBoundingBox
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonDash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PersonX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Phone
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PhoneLandscape
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PhoneVibrate
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PieChart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PiggyBank
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pin
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PinAngle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PinMap
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Pip
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Play
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlayBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlayCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Plug
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Plus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlusCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlusCircleDotted
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlusLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlusSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.PlusSquareDotted
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Power
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Printer
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Puzzle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Question
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.QuestionCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.QuestionDiamond
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.QuestionLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.QuestionOctagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.QuestionSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Rainbow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Receipt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ReceiptCutoff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reception0
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reception1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reception2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reception3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reception4
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Record
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Record2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.RecordBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.RecordCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Recycle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reddit
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Reply
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ReplyAll
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Rss
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Rulers
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Safe
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Safe2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Save
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Save2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Scissors
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Screwdriver
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SdCard
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Search
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SegmentedNav
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Server
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Share
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Shield
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldCheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldExclamation
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldLock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldPlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldShaded
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldSlash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShieldX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Shift
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Shop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ShopWindow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Shuffle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Signpost
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Signpost2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SignpostSplit
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sim
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipBackward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipBackwardBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipBackwardCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipEnd
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipEndBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipEndCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipForward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipForwardBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipForwardCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipStart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipStartBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SkipStartCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Skype
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Slack
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Slash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SlashCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SlashLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SlashSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sliders
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Smartwatch
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Snow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Snow2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Snow3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortAlphaDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortAlphaDownAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortAlphaUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortAlphaUpAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortDownAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortNumericDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortNumericDownAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortNumericUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortNumericUpAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SortUpAlt
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Soundwave
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Speaker
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Speedometer
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Speedometer2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Spellcheck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Square
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SquareHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stack
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Star
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.StarHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stars
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stickies
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sticky
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stop
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.StopBtn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.StopCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stoplights
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Stopwatch
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Subtract
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SuitClub
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SuitDiamond
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SuitHeart
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SuitSpade
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sun
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sunglasses
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sunrise
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Sunset
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SymmetryHorizontal
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.SymmetryVertical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Table
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tablet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TabletLandscape
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tag
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tags
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Telegram
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Telephone
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephoneForward
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephoneInbound
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephoneMinus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephoneOutbound
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephonePlus
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TelephoneX
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Terminal
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextCenter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextIndentLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextIndentRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextLeft
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextParagraph
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextRight
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Textarea
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextareaResize
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TextareaT
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Thermometer
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThermometerHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThermometerHigh
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThermometerLow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThermometerSnow
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThermometerSun
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThreeDots
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ThreeDotsVertical
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Toggle2Off
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Toggle2On
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ToggleOff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ToggleOn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Toggles
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Toggles2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tools
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tornado
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Translate
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Trash
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Trash2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tree
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Triangle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TriangleHalf
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Trophy
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TropicalStorm
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Truck
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TruckFlatbed
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tsunami
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Tv
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Twitch
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Twitter
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Type
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeBold
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeH1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeH2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeH3
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeItalic
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeStrikethrough
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.TypeUnderline
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.UiChecks
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.UiChecksGrid
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.UiRadios
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.UiRadiosGrid
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Umbrella
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Union
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Unlock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Upc
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.UpcScan
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Upload
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.VectorPen
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ViewList
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ViewStacked
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Vinyl
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Voicemail
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.VolumeDown
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.VolumeMute
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.VolumeOff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.VolumeUp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Vr
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wallet
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wallet2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Watch
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Water
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Whatsapp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wifi
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wifi1
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wifi2
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.WifiOff
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wind
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Window
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.WindowDock
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.WindowSidebar
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Wrench
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.X
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.XCircle
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.XDiamond
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.XLg
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.XOctagon
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.XSquare
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.Youtube
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ZoomIn
import com.wiryadev.bootstrapiconscompose.bootstrapicons.normal.ZoomOut
import kotlin.collections.List as ____KtList

public object NormalGroup

public val BootstrapIcons.Normal: NormalGroup
  get() = NormalGroup

private var __AllAssets: ____KtList<ImageVector>? = null

public val NormalGroup.AllAssets: ____KtList<ImageVector>
  get() {
    if (__AllAssets != null) {
      return __AllAssets!!
    }
    __AllAssets= listOf(Alarm, AlignBottom, AlignCenter, AlignEnd, AlignMiddle, AlignStart,
        AlignTop, Alt, App, AppIndicator, Archive, ArrowsAngleContract, ArrowsAngleExpand,
        ArrowsCollapse, ArrowsExpand, ArrowsFullscreen, ArrowsMove, Arrow90degDown, Arrow90degLeft,
        Arrow90degRight, Arrow90degUp, ArrowBarDown, ArrowBarLeft, ArrowBarRight, ArrowBarUp,
        ArrowClockwise, ArrowCounterclockwise, ArrowDown, ArrowDownCircle, ArrowDownLeft,
        ArrowDownLeftCircle, ArrowDownLeftSquare, ArrowDownRight, ArrowDownRightCircle,
        ArrowDownRightSquare, ArrowDownShort, ArrowDownSquare, ArrowDownUp, ArrowLeft,
        ArrowLeftCircle, ArrowLeftRight, ArrowLeftShort, ArrowLeftSquare, ArrowRepeat,
        ArrowReturnLeft, ArrowReturnRight, ArrowRight, ArrowRightCircle, ArrowRightShort,
        ArrowRightSquare, ArrowUp, ArrowUpCircle, ArrowUpLeft, ArrowUpLeftCircle, ArrowUpLeftSquare,
        ArrowUpRight, ArrowUpRightCircle, ArrowUpRightSquare, ArrowUpShort, ArrowUpSquare,
        AspectRatio, Asterisk, At, Award, Back, Backspace, BackspaceReverse, Badge3d, Badge4k,
        Badge8k, BadgeAd, BadgeAr, BadgeCc, BadgeHd, BadgeTm, BadgeVo, BadgeVr, BadgeWc, Bag,
        BagCheck, BagDash, BagPlus, BagX, Bank, Bank2, BarChart, BarChartLine, BarChartSteps,
        Basket, Basket2, Basket3, Battery, BatteryCharging, BatteryFull, BatteryHalf, Bell,
        BellSlash, Bezier, Bezier2, Bicycle, Binoculars, BlockquoteLeft, BlockquoteRight, Book,
        Bookmark, Bookmarks, BookmarkCheck, BookmarkDash, BookmarkHeart, BookmarkPlus, BookmarkStar,
        BookmarkX, Bookshelf, BookHalf, Bootstrap, BootstrapReboot, Border, BorderAll, BorderBottom,
        BorderCenter, BorderInner, BorderLeft, BorderMiddle, BorderOuter, BorderRight, BorderStyle,
        BorderTop, BorderWidth, BoundingBox, BoundingBoxCircles, Box, BoxArrowDown,
        BoxArrowDownLeft, BoxArrowDownRight, BoxArrowInDown, BoxArrowInDownLeft,
        BoxArrowInDownRight, BoxArrowInLeft, BoxArrowInRight, BoxArrowInUp, BoxArrowInUpLeft,
        BoxArrowInUpRight, BoxArrowLeft, BoxArrowRight, BoxArrowUp, BoxArrowUpLeft, BoxArrowUpRight,
        BoxSeam, Braces, Bricks, Briefcase, BrightnessAltHigh, BrightnessAltLow, BrightnessHigh,
        BrightnessLow, Broadcast, BroadcastPin, Brush, Bucket, Bug, Building, Bullseye, Calculator,
        Calendar, Calendar2, Calendar2Check, Calendar2Date, Calendar2Day, Calendar2Event,
        Calendar2Minus, Calendar2Month, Calendar2Plus, Calendar2Range, Calendar2Week, Calendar2X,
        Calendar3, Calendar3Event, Calendar3Range, Calendar3Week, Calendar4, Calendar4Event,
        Calendar4Range, Calendar4Week, CalendarCheck, CalendarDate, CalendarDay, CalendarEvent,
        CalendarMinus, CalendarMonth, CalendarPlus, CalendarRange, CalendarWeek, CalendarX, Camera,
        Camera2, CameraReels, CameraVideo, CameraVideoOff, Capslock, CardChecklist, CardHeading,
        CardImage, CardList, CardText, CaretDown, CaretDownSquare, CaretLeft, CaretLeftSquare,
        CaretRight, CaretRightSquare, CaretUp, CaretUpSquare, Cart, Cart2, Cart3, Cart4, CartCheck,
        CartDash, CartPlus, CartX, Cash, CashCoin, CashStack, Cast, Chat, ChatDots, ChatLeft,
        ChatLeftDots, ChatLeftQuote, ChatLeftText, ChatQuote, ChatRight, ChatRightDots,
        ChatRightQuote, ChatRightText, ChatSquare, ChatSquareDots, ChatSquareQuote, ChatSquareText,
        ChatText, Check, Check2, Check2All, Check2Circle, Check2Square, CheckAll, CheckCircle,
        CheckLg, CheckSquare, ChevronBarContract, ChevronBarDown, ChevronBarExpand, ChevronBarLeft,
        ChevronBarRight, ChevronBarUp, ChevronCompactDown, ChevronCompactLeft, ChevronCompactRight,
        ChevronCompactUp, ChevronContract, ChevronDoubleDown, ChevronDoubleLeft, ChevronDoubleRight,
        ChevronDoubleUp, ChevronDown, ChevronExpand, ChevronLeft, ChevronRight, ChevronUp, Circle,
        CircleHalf, CircleSquare, Clipboard, ClipboardCheck, ClipboardData, ClipboardMinus,
        ClipboardPlus, ClipboardX, Clock, ClockHistory, Cloud, Clouds, Cloudy, CloudArrowDown,
        CloudArrowUp, CloudCheck, CloudDownload, CloudDrizzle, CloudFog, CloudFog2, CloudHail,
        CloudHaze, CloudHaze1, CloudLightning, CloudLightningRain, CloudMinus, CloudMoon, CloudPlus,
        CloudRain, CloudRainHeavy, CloudSlash, CloudSleet, CloudSnow, CloudSun, CloudUpload, Code,
        CodeSlash, CodeSquare, Coin, Collection, CollectionPlay, Columns, ColumnsGap, Command,
        Compass, Cone, ConeStriped, Controller, Cpu, CreditCard, CreditCard2Back, CreditCard2Front,
        Crop, Cup, CupStraw, CurrencyBitcoin, CurrencyDollar, CurrencyEuro, CurrencyExchange,
        CurrencyPound, CurrencyYen, Cursor, CursorText, Dash, DashCircle, DashCircleDotted, DashLg,
        DashSquare, DashSquareDotted, Diagram2, Diagram3, Diamond, DiamondHalf, Dice1, Dice2, Dice3,
        Dice4, Dice5, Dice6, Disc, Discord, Display, DistributeHorizontal, DistributeVertical,
        DoorClosed, DoorOpen, Dot, Download, Droplet, DropletHalf, Earbuds, Easel, Egg, EggFried,
        Eject, EmojiAngry, EmojiDizzy, EmojiExpressionless, EmojiFrown, EmojiHeartEyes,
        EmojiLaughing, EmojiNeutral, EmojiSmile, EmojiSmileUpsideDown, EmojiSunglasses, EmojiWink,
        Envelope, EnvelopeOpen, Eraser, Exclamation, ExclamationCircle, ExclamationDiamond,
        ExclamationLg, ExclamationOctagon, ExclamationSquare, ExclamationTriangle, Exclude, Eye,
        Eyedropper, Eyeglasses, EyeSlash, Facebook, File, Files, FilesAlt, FileArrowDown,
        FileArrowUp, FileBarGraph, FileBinary, FileBreak, FileCheck, FileCode, FileDiff,
        FileEarmark, FileEarmarkArrowDown, FileEarmarkArrowUp, FileEarmarkBarGraph,
        FileEarmarkBinary, FileEarmarkBreak, FileEarmarkCheck, FileEarmarkCode, FileEarmarkDiff,
        FileEarmarkEasel, FileEarmarkExcel, FileEarmarkFont, FileEarmarkImage, FileEarmarkLock,
        FileEarmarkLock2, FileEarmarkMedical, FileEarmarkMinus, FileEarmarkMusic, FileEarmarkPdf,
        FileEarmarkPerson, FileEarmarkPlay, FileEarmarkPlus, FileEarmarkPost, FileEarmarkPpt,
        FileEarmarkRichtext, FileEarmarkRuled, FileEarmarkSlides, FileEarmarkSpreadsheet,
        FileEarmarkText, FileEarmarkWord, FileEarmarkX, FileEarmarkZip, FileEasel, FileExcel,
        FileFont, FileImage, FileLock, FileLock2, FileMedical, FileMinus, FileMusic, FilePdf,
        FilePerson, FilePlay, FilePlus, FilePost, FilePpt, FileRichtext, FileRuled, FileSlides,
        FileSpreadsheet, FileText, FileWord, FileX, FileZip, Film, Filter, FilterCircle, FilterLeft,
        FilterRight, FilterSquare, Flag, Flower1, Flower2, Flower3, Folder, Folder2, Folder2Open,
        FolderCheck, FolderMinus, FolderPlus, FolderSymlink, FolderX, Fonts, Forward, Front,
        Fullscreen, FullscreenExit, Funnel, Gear, GearWide, GearWideConnected, Gem, GenderAmbiguous,
        GenderFemale, GenderMale, GenderTrans, Geo, GeoAlt, Gift, Github, Globe, Globe2, Google,
        GraphDown, GraphUp, Grid, Grid1x2, Grid3x2, Grid3x2Gap, Grid3x3, Grid3x3Gap, GripHorizontal,
        GripVertical, Hammer, Handbag, HandIndex, HandIndexThumb, HandThumbsDown, HandThumbsUp,
        Hash, Hdd, HddNetwork, HddRack, HddStack, Headphones, Headset, HeadsetVr, Heart, HeartHalf,
        Heptagon, HeptagonHalf, Hexagon, HexagonHalf, Hourglass, HourglassBottom, HourglassSplit,
        HourglassTop, House, HouseDoor, Hr, Hurricane, Image, Images, ImageAlt, Inbox, Inboxes,
        Info, InfoCircle, InfoLg, InfoSquare, InputCursor, InputCursorText, Instagram, Intersect,
        Journal, Journals, JournalAlbum, JournalArrowDown, JournalArrowUp, JournalBookmark,
        JournalCheck, JournalCode, JournalMedical, JournalMinus, JournalPlus, JournalRichtext,
        JournalText, JournalX, Joystick, Justify, JustifyLeft, JustifyRight, Kanban, Key, Keyboard,
        Ladder, Lamp, Laptop, Layers, LayersHalf, LayerBackward, LayerForward, LayoutSidebar,
        LayoutSidebarInset, LayoutSidebarInsetReverse, LayoutSidebarReverse, LayoutSplit,
        LayoutTextSidebar, LayoutTextSidebarReverse, LayoutTextWindow, LayoutTextWindowReverse,
        LayoutThreeColumns, LayoutWtf, LifePreserver, Lightbulb, LightbulbOff, Lightning,
        LightningCharge, Link, Linkedin, Link45deg, List, ListCheck, ListNested, ListOl, ListStars,
        ListTask, ListUl, Lock, Mailbox, Mailbox2, Map, Markdown, Mask, Mastodon, Megaphone,
        MenuApp, MenuButton, MenuButtonWide, MenuDown, MenuUp, Messenger, Mic, MicMute, Minecart,
        MinecartLoaded, Moisture, Moon, MoonStars, Mouse, Mouse2, Mouse3, MusicNote,
        MusicNoteBeamed, MusicNoteList, MusicPlayer, Newspaper, NodeMinus, NodePlus, Nut, Octagon,
        OctagonHalf, Option, Outlet, PaintBucket, Palette, Palette2, Paperclip, Paragraph,
        PatchCheck, PatchExclamation, PatchMinus, PatchPlus, PatchQuestion, Pause, PauseBtn,
        PauseCircle, Peace, Pen, Pencil, PencilSquare, Pentagon, PentagonHalf, People, Percent,
        Person, PersonBadge, PersonBoundingBox, PersonCheck, PersonCircle, PersonDash, PersonPlus,
        PersonSquare, PersonX, Phone, PhoneLandscape, PhoneVibrate, PieChart, PiggyBank, Pin,
        PinAngle, PinMap, Pip, Play, PlayBtn, PlayCircle, Plug, Plus, PlusCircle, PlusCircleDotted,
        PlusLg, PlusSquare, PlusSquareDotted, Power, Printer, Puzzle, Question, QuestionCircle,
        QuestionDiamond, QuestionLg, QuestionOctagon, QuestionSquare, Rainbow, Receipt,
        ReceiptCutoff, Reception0, Reception1, Reception2, Reception3, Reception4, Record, Record2,
        RecordBtn, RecordCircle, Recycle, Reddit, Reply, ReplyAll, Rss, Rulers, Safe, Safe2, Save,
        Save2, Scissors, Screwdriver, SdCard, Search, SegmentedNav, Server, Share, Shield,
        ShieldCheck, ShieldExclamation, ShieldLock, ShieldMinus, ShieldPlus, ShieldShaded,
        ShieldSlash, ShieldX, Shift, Shop, ShopWindow, Shuffle, Signpost, Signpost2, SignpostSplit,
        Sim, SkipBackward, SkipBackwardBtn, SkipBackwardCircle, SkipEnd, SkipEndBtn, SkipEndCircle,
        SkipForward, SkipForwardBtn, SkipForwardCircle, SkipStart, SkipStartBtn, SkipStartCircle,
        Skype, Slack, Slash, SlashCircle, SlashLg, SlashSquare, Sliders, Smartwatch, Snow, Snow2,
        Snow3, SortAlphaDown, SortAlphaDownAlt, SortAlphaUp, SortAlphaUpAlt, SortDown, SortDownAlt,
        SortNumericDown, SortNumericDownAlt, SortNumericUp, SortNumericUpAlt, SortUp, SortUpAlt,
        Soundwave, Speaker, Speedometer, Speedometer2, Spellcheck, Square, SquareHalf, Stack, Star,
        Stars, StarHalf, Stickies, Sticky, Stop, Stoplights, Stopwatch, StopBtn, StopCircle,
        Subtract, SuitClub, SuitDiamond, SuitHeart, SuitSpade, Sun, Sunglasses, Sunrise, Sunset,
        SymmetryHorizontal, SymmetryVertical, Table, Tablet, TabletLandscape, Tag, Tags, Telegram,
        Telephone, TelephoneForward, TelephoneInbound, TelephoneMinus, TelephoneOutbound,
        TelephonePlus, TelephoneX, Terminal, Textarea, TextareaResize, TextareaT, TextCenter,
        TextIndentLeft, TextIndentRight, TextLeft, TextParagraph, TextRight, Thermometer,
        ThermometerHalf, ThermometerHigh, ThermometerLow, ThermometerSnow, ThermometerSun,
        ThreeDots, ThreeDotsVertical, Toggle2Off, Toggle2On, Toggles, Toggles2, ToggleOff, ToggleOn,
        Tools, Tornado, Translate, Trash, Trash2, Tree, Triangle, TriangleHalf, Trophy,
        TropicalStorm, Truck, TruckFlatbed, Tsunami, Tv, Twitch, Twitter, Type, TypeBold, TypeH1,
        TypeH2, TypeH3, TypeItalic, TypeStrikethrough, TypeUnderline, UiChecks, UiChecksGrid,
        UiRadios, UiRadiosGrid, Umbrella, Union, Unlock, Upc, UpcScan, Upload, VectorPen, ViewList,
        ViewStacked, Vinyl, Voicemail, VolumeDown, VolumeMute, VolumeOff, VolumeUp, Vr, Wallet,
        Wallet2, Watch, Water, Whatsapp, Wifi, Wifi1, Wifi2, WifiOff, Wind, Window, WindowDock,
        WindowSidebar, Wrench, X, XCircle, XDiamond, XLg, XOctagon, XSquare, Youtube, ZoomIn,
        ZoomOut)
    return __AllAssets!!
  }
