package com.wiryadev.bootstrapiconscompose.bootstrapicons.normal

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.NormalGroup

public val NormalGroup.Border: ImageVector
    get() {
        if (_border != null) {
            return _border!!
        }
        _border = Builder(name = "Border", defaultWidth = 16.0.dp, defaultHeight = 16.0.dp,
                viewportWidth = 16.0f, viewportHeight = 16.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(0.0f, 0.0f)
                horizontalLineToRelative(0.969f)
                verticalLineToRelative(0.5f)
                lineTo(1.0f, 0.5f)
                verticalLineToRelative(0.469f)
                lineTo(0.969f, 0.969f)
                lineTo(0.969f, 1.0f)
                lineTo(0.5f, 1.0f)
                lineTo(0.5f, 0.969f)
                lineTo(0.0f, 0.969f)
                lineTo(0.0f, 0.0f)
                close()
                moveTo(2.844f, 1.0f)
                horizontalLineToRelative(-0.938f)
                lineTo(1.906f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(4.719f, 1.0f)
                lineTo(3.78f, 1.0f)
                lineTo(3.78f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(6.594f, 1.0f)
                horizontalLineToRelative(-0.938f)
                lineTo(5.656f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(7.531f, 1.0f)
                lineTo(7.531f, 0.969f)
                lineTo(7.5f, 0.969f)
                lineTo(7.5f, 0.5f)
                horizontalLineToRelative(0.031f)
                lineTo(7.531f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(0.5f)
                lineTo(8.5f, 0.5f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(-0.031f)
                lineTo(8.469f, 1.0f)
                lineTo(7.53f, 1.0f)
                close()
                moveTo(10.344f, 1.0f)
                horizontalLineToRelative(-0.938f)
                lineTo(9.406f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(12.219f, 1.0f)
                horizontalLineToRelative(-0.938f)
                lineTo(11.281f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(14.094f, 1.0f)
                horizontalLineToRelative(-0.938f)
                lineTo(13.156f, 0.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(15.5f, 1.0f)
                horizontalLineToRelative(-0.469f)
                lineTo(15.031f, 0.969f)
                lineTo(15.0f, 0.969f)
                lineTo(15.0f, 0.5f)
                horizontalLineToRelative(0.031f)
                lineTo(15.031f, 0.0f)
                lineTo(16.0f, 0.0f)
                verticalLineToRelative(0.969f)
                horizontalLineToRelative(-0.5f)
                lineTo(15.5f, 1.0f)
                close()
                moveTo(1.0f, 1.906f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 2.844f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 2.844f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 2.844f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(1.0f, 3.78f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 4.718f)
                lineTo(0.0f, 3.78f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 4.718f)
                lineTo(7.5f, 3.78f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 4.718f)
                lineTo(15.0f, 3.78f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(1.0f, 5.656f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 6.594f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 6.594f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 6.594f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(0.969f, 8.5f)
                lineTo(0.5f, 8.5f)
                verticalLineToRelative(-0.031f)
                lineTo(0.0f, 8.469f)
                lineTo(0.0f, 7.53f)
                horizontalLineToRelative(0.5f)
                lineTo(0.5f, 7.5f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(0.031f)
                lineTo(1.0f, 7.531f)
                verticalLineToRelative(0.938f)
                lineTo(0.969f, 8.469f)
                lineTo(0.969f, 8.5f)
                close()
                moveTo(2.844f, 8.5f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(4.719f, 8.5f)
                lineTo(3.78f, 8.5f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(6.594f, 8.5f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(8.469f, 8.469f)
                lineTo(8.469f, 8.5f)
                lineTo(7.53f, 8.5f)
                verticalLineToRelative(-0.031f)
                lineTo(7.5f, 8.469f)
                lineTo(7.5f, 7.53f)
                horizontalLineToRelative(0.031f)
                lineTo(7.531f, 7.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(0.031f)
                lineTo(8.5f, 7.531f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-0.031f)
                close()
                moveTo(10.344f, 8.5f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(12.219f, 8.5f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(14.094f, 8.5f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(15.5f, 8.5f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(-0.031f)
                lineTo(15.0f, 8.469f)
                lineTo(15.0f, 7.53f)
                horizontalLineToRelative(0.031f)
                lineTo(15.031f, 7.5f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(0.031f)
                horizontalLineToRelative(0.5f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-0.5f)
                lineTo(15.5f, 8.5f)
                close()
                moveTo(0.0f, 10.344f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 10.344f)
                close()
                moveTo(7.5f, 10.344f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 9.406f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.0f, 12.22f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 12.22f)
                close()
                moveTo(7.5f, 12.22f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 11.282f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.0f, 14.094f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                lineTo(0.0f, 14.094f)
                close()
                moveTo(7.5f, 14.094f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 13.156f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.969f, 16.0f)
                lineTo(0.0f, 16.0f)
                verticalLineToRelative(-0.969f)
                horizontalLineToRelative(0.5f)
                lineTo(0.5f, 15.0f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(0.031f)
                lineTo(1.0f, 15.031f)
                verticalLineToRelative(0.469f)
                lineTo(0.969f, 15.5f)
                verticalLineToRelative(0.5f)
                close()
                moveTo(2.844f, 16.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(4.719f, 16.0f)
                lineTo(3.78f, 16.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(6.594f, 16.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(7.531f, 16.0f)
                verticalLineToRelative(-0.5f)
                lineTo(7.5f, 15.5f)
                verticalLineToRelative(-0.469f)
                horizontalLineToRelative(0.031f)
                lineTo(7.531f, 15.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(0.031f)
                lineTo(8.5f, 15.031f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(-0.031f)
                verticalLineToRelative(0.5f)
                lineTo(7.53f, 16.0f)
                close()
                moveTo(10.344f, 16.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(12.219f, 16.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(14.094f, 16.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(15.031f, 16.0f)
                verticalLineToRelative(-0.5f)
                lineTo(15.0f, 15.5f)
                verticalLineToRelative(-0.469f)
                horizontalLineToRelative(0.031f)
                lineTo(15.031f, 15.0f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(0.031f)
                horizontalLineToRelative(0.5f)
                lineTo(16.0f, 16.0f)
                horizontalLineToRelative(-0.969f)
                close()
            }
        }
        .build()
        return _border!!
    }

private var _border: ImageVector? = null
