package com.wiryadev.bootstrapiconscompose.bootstrapicons.normal

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.wiryadev.bootstrapiconscompose.bootstrapicons.NormalGroup

public val NormalGroup.BorderTop: ImageVector
    get() {
        if (_borderTop != null) {
            return _borderTop!!
        }
        _borderTop = Builder(name = "BorderTop", defaultWidth = 16.0.dp, defaultHeight = 16.0.dp,
                viewportWidth = 16.0f, viewportHeight = 16.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(0.0f, 0.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(16.0f)
                lineTo(16.0f, 0.0f)
                lineTo(0.0f, 0.0f)
                close()
                moveTo(1.0f, 2.844f)
                verticalLineToRelative(-0.938f)
                lineTo(0.0f, 1.906f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 1.906f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 1.906f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(1.0f, 4.719f)
                lineTo(1.0f, 3.78f)
                lineTo(0.0f, 3.78f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 3.781f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                lineTo(8.5f, 3.78f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 3.781f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                lineTo(16.0f, 3.78f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(1.0f, 6.594f)
                verticalLineToRelative(-0.938f)
                lineTo(0.0f, 5.656f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.5f, 5.656f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.0f, 5.656f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(0.5f, 8.5f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(-0.031f)
                lineTo(1.0f, 8.469f)
                lineTo(1.0f, 7.53f)
                lineTo(0.969f, 7.53f)
                lineTo(0.969f, 7.5f)
                lineTo(0.5f, 7.5f)
                verticalLineToRelative(0.031f)
                lineTo(0.0f, 7.531f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(0.5f)
                lineTo(0.5f, 8.5f)
                close()
                moveTo(1.906f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(3.781f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                lineTo(3.78f, 7.5f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(5.656f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(8.469f, 8.5f)
                verticalLineToRelative(-0.031f)
                lineTo(8.5f, 8.469f)
                lineTo(8.5f, 7.53f)
                horizontalLineToRelative(-0.031f)
                lineTo(8.469f, 7.5f)
                lineTo(7.53f, 7.5f)
                verticalLineToRelative(0.031f)
                lineTo(7.5f, 7.531f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(0.031f)
                lineTo(7.531f, 8.5f)
                horizontalLineToRelative(0.938f)
                close()
                moveTo(9.406f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(11.281f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(13.156f, 8.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(15.031f, 8.5f)
                horizontalLineToRelative(0.469f)
                verticalLineToRelative(-0.031f)
                horizontalLineToRelative(0.5f)
                lineTo(16.0f, 7.53f)
                horizontalLineToRelative(-0.5f)
                lineTo(15.5f, 7.5f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(0.031f)
                lineTo(15.0f, 7.531f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(0.031f)
                lineTo(15.031f, 8.5f)
                close()
                moveTo(0.0f, 9.406f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                lineTo(0.0f, 9.406f)
                close()
                moveTo(7.5f, 9.406f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 10.344f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.0f, 11.281f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                lineTo(0.0f, 11.281f)
                close()
                moveTo(7.5f, 11.281f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 12.219f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.0f, 13.156f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                lineTo(0.0f, 13.156f)
                close()
                moveTo(7.5f, 13.156f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(16.0f, 14.094f)
                verticalLineToRelative(-0.938f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.938f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(0.0f, 16.0f)
                horizontalLineToRelative(0.969f)
                verticalLineToRelative(-0.5f)
                lineTo(1.0f, 15.5f)
                verticalLineToRelative(-0.469f)
                lineTo(0.969f, 15.031f)
                lineTo(0.969f, 15.0f)
                lineTo(0.5f, 15.0f)
                verticalLineToRelative(0.031f)
                lineTo(0.0f, 15.031f)
                lineTo(0.0f, 16.0f)
                close()
                moveTo(1.906f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(3.781f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                lineTo(3.78f, 15.0f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(5.656f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(7.531f, 15.5f)
                verticalLineToRelative(0.5f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-0.5f)
                lineTo(8.5f, 15.5f)
                verticalLineToRelative(-0.469f)
                horizontalLineToRelative(-0.031f)
                lineTo(8.469f, 15.0f)
                lineTo(7.53f, 15.0f)
                verticalLineToRelative(0.031f)
                lineTo(7.5f, 15.031f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(0.031f)
                close()
                moveTo(9.406f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(11.281f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(13.156f, 16.0f)
                horizontalLineToRelative(0.938f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.938f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(15.031f, 15.5f)
                verticalLineToRelative(0.5f)
                lineTo(16.0f, 16.0f)
                verticalLineToRelative(-0.969f)
                horizontalLineToRelative(-0.5f)
                lineTo(15.5f, 15.0f)
                horizontalLineToRelative(-0.469f)
                verticalLineToRelative(0.031f)
                lineTo(15.0f, 15.031f)
                verticalLineToRelative(0.469f)
                horizontalLineToRelative(0.031f)
                close()
            }
        }
        .build()
        return _borderTop!!
    }

private var _borderTop: ImageVector? = null
